feat: bundle analyzer endpoint added
qiwi-forks/polyfill-service pull request #2
Opened 2022-10-19 09:41 UTC by lpk3nny

2022-10-20 12:30 UTC, antongolub requested changes

2022-10-20 12:30 UTC, antongolub commented on server/routes/__analyze.js
> +			file: bundleFileNames, cwd: `./${uploadDestination}`,
let's use `tempy.temporaryDirectory()`

2022-10-20 17:54 UTC, antongolub requested changes

2022-10-20 17:54 UTC, antongolub commented on server/utils/config.js
>  		if (process.env.SERVE_STATIC_SITE) return Boolean(process.env.SERVE_STATIC_SITE);
Boolean('false') → true. Boolean('0') → true.
Let's add util parseBool helper:
```js
parseBool = (value) => value === 'true' || value === '1' || value === 1 || value === true || false
```

2022-10-20 17:57 UTC, antongolub reviewed
Almost LGTM)

2022-10-21 07:35 UTC, lpk3nny commented on server/utils/config.js
>  		if (process.env.SERVE_STATIC_SITE) return Boolean(process.env.SERVE_STATIC_SITE);
ri-ight

2022-10-21 07:56 UTC, antongolub approved these changes

2022-10-21 07:57 UTC, merged